# Generated by Django 4.2.3 on 2023-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='購入日'),
        ),
    ]
