# Generated by Django 4.2.3 on 2023-07-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0002_toys_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='toys',
            table='blogs',
        ),
    ]
