# Generated by Django 4.2.3 on 2023-07-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_alter_toys_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='freq',
            field=models.CharField(blank=True, choices=[('たまに', 'たまに'), ('よく', 'よく'), ('いつも', 'いつも')], max_length=50),
        ),
    ]
