# Generated by Django 4.2.3 on 2023-07-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_alter_toys_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='freq',
            field=models.CharField(blank=True, choices=[('ほぼ使わない', 'ほぼ使わない'), ('たまに', 'たまに'), ('いつも', 'いつも')], max_length=50, verbose_name='頻度'),
        ),
    ]
