# Generated by Django 4.2.3 on 2023-07-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_alter_toys_freq'),
    ]

    operations = [
        migrations.AddField(
            model_name='toys',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='toys',
            name='name',
            field=models.CharField(max_length=32, verbose_name='おもちゃ名'),
        ),
    ]
