# Generated by Django 4.2.3 on 2023-07-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_toys_image_alter_toys_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toys',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media_local'),
        ),
    ]
