# Generated by Django 3.2.18 on 2023-07-27 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0008_alter_toys_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='toys',
            name='tags',
            field=models.ManyToManyField(blank=True, to='toys.Tag'),
        ),
    ]
