# Generated by Django 3.2.18 on 2023-07-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0009_auto_20230727_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toys',
            name='tags',
        ),
        migrations.AddField(
            model_name='toys',
            name='tags',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='タグ'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
