# Generated by Django 4.2.3 on 2023-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0010_auto_20230727_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='タグ')),
            ],
        ),
        migrations.RemoveField(
            model_name='toys',
            name='tags',
        ),
        migrations.AddField(
            model_name='toys',
            name='tags',
            field=models.ManyToManyField(blank=True, to='toys.tag'),
        ),
    ]
